### ISSUE TITLE
Broken links documentation

### ISSUE THREAD

**Issue by olivierbonte** [EarthyScience/Bigleaf.jl#42]
Hi, 

First of all, a major thanks to @bgctw for this package, I really enjoyed using it so far!

Since the package has been moved from the personal github of @bgctw to the EarthyScience organisation, the url of where the documentation is hosted has changed, but this has not yet been updated in the README.

**Comment by bgctw** [comment]
Thank you @olivierbonte for reminding me to update the links and for you pull request. Rather than merging you PR, I consistently replaced all references to bgctw also across other files, and changed also the codecov setup.
